### PR TITLE
fix: add undeclared dependency `lodash`

### PR DESCRIPTION
**Pull request by merceyz**
**What's the problem this PR addresses?**

`query-ast` depends on `lodash` but doesn't declare it as a dependency

**How did you fix it?**

Added `lodash` as a dependency

### CODE REVIEW

**Comment by jcreamer898** [comment]
Same here. Haha. Need this fixed.

**Comment by iclanton** [comment]
@alexiscordova, @fredboyle, and @zahnster were recent contributors to this repository. Can one of you look at this issue?

**Comment by alexiscordova** [comment]
@iclanton none of the folks you listed work at Salesforce anymore. @Dottenpixel might be your best bet

**Comment by Dottenpixel** [comment]
Cheers @alexiscordova! 

@merceyz, thank you for your contribution. We usually have a bot that prompts contributors to sign a contributor's licensing agreement (CLA) before accepting their PRs. I've just enabled the bot on this repo.

We can make the change internally, or if you'd like recreate this PR and sign the CLA when prompted by the bot.

**Comment by merceyz** [comment]
I've already signed the CLA, ref https://github.com/salesforce-ux/scss-parser/pull/43#event-5033927491.

**Comment by Dottenpixel** [comment]
> I've already signed the CLA, ref [salesforce-ux/scss-parser#43 (comment)](https://github.com/salesforce-ux/scss-parser/pull/43#event-5033927491).

Right on, reopening the PR and merging. Thanks again @merceyz!

**Review by Dottenpixel — APPROVED** [review]

**Pull request merged**
